// Domain-owned compositions. IDs are the shared persistence/render contract.
const R='<div id="records"></div>',T='<div id="workspace-toolbar"></div>',S='<section id="summary" aria-live="polite"></section>',D='<div id="details"></div>';
const dialog=()=>`<dialog id="edit-dialog" aria-label="Рабочая панель"><button class="close-dialog" data-close-dialog aria-label="Закрыть панель">×</button>${D}</dialog>`;
const add=text=>`<button class="primary-action" data-open-dialog>${text}</button>`;
const photo=(name,alt)=>`<img src="../assets/photos/${name}.jpg" alt="${alt}">`;
const nav=(brand,links)=>`<header class="brand-header"><a class="wordmark" href="#workspace">${brand}</a><nav>${links}</nav><a class="back" href="../index.html#work">Портфолио ↗</a></header>`;
module.exports=type=>{
switch(type){
case 'finance':return `<div class="ledger-app"><aside class="ledger-rail"><a class="wordmark" href="#workspace">Реестр<small>Финансы студии</small></a><nav><a href="#workspace">Счета клиентов</a><a href="#activity-section">Операции</a><a href="#open-data">Курсы валют</a></nav><a href="../index.html#work">← Портфолио</a></aside><main id="workspace"><header class="ledger-title"><div><p>Студия / Финансы</p><h1>Счета и оплаты</h1></div>${add('+ Выставить счёт')}</header>${S}<section class="ledger-sheet">${T}${R}</section>${dialog()}</main></div>`;
case 'hiring':return `${nav('Состав','<a href="#workspace">Кандидаты</a><a href="#activity-section">Активность</a>')}<main id="workspace" class="recruit-page"><div class="recruit-title"><div><p>Продуктовая команда</p><h1>Собираем сильную команду.</h1></div>${S}</div><div class="board-tools">${T}${add('+ Кандидат')}</div>${R}${dialog()}</main>`;
case 'kitchen':return `<main id="workspace" class="kitchen-book"><aside class="kitchen-cover">${photo('kitchen','Рабочая кухня ресторана')}<div class="cover-text"><a href="../index.html#work">← Портфолио</a><p>СМЕНА · КНИГА ЗАГОТОВОК</p><h1>До первого<br>заказа.</h1><p>Объёмы, цеха и готовность кухни.</p></div></aside><div class="kitchen-work"><header><p>План производства</p>${S}</header><section class="guest-counter">${D}</section>${T}${R}</div></main>`;
case 'warehouse':return `${nav('МАРШРУТ','<a href="#workspace">Отгрузки</a><a href="#activity-section">Журнал смены</a>')}<main id="workspace" class="dispatch-page"><div class="dispatch-heading"><div><p>СКЛАД / ИСХОДЯЩИЙ ПОТОК</p><h1>Контроль отгрузки</h1></div>${add('+ Создать отгрузку')}</div>${S}<div class="dispatch-toolbar">${T}</div>${R}${dialog()}</main>`;
case 'personal':return `${nav('ритм','<a href="#workspace">Эта неделя</a><a href="#activity-section">Мои отметки</a>')}<main id="workspace" class="journal"><header class="journal-title"><p>Личный дневник привычек</p><h1>В своём ритме.</h1><p>У каждого дня свой маленький шаг.</p></header><div class="journal-sheet">${S}${T}${R}<details class="add-habit"><summary>＋ Ещё одна привычка</summary>${D}</details></div><p class="journal-note">Один пропущенный день ничего не обнуляет.<br>Продолжайте с того места, где вы сейчас.</p></main>`;
case 'academy':return `<main id="workspace" class="learning-room"><aside class="course-outline"><a class="wordmark" href="#workspace">Практика</a><p>Frontend · группа 04</p><h1>От макета <br>к интерфейсу</h1>${S}${T}${R}<a href="../index.html#work">← Портфолио</a></aside><article class="lesson-paper"><header><span>Кабинет наставника / Проверка работы</span><a href="#open-data">Библиотека ↗</a></header>${D}</article></main>`;
case 'estate':return `${nav('АДРЕС','<a href="#catalogue">Квартиры</a><a href="#workspace-toolbar">Подбор для клиента</a>')}<main id="workspace"><section class="estate-cover"><div><p>КАЗАНЬ · ЖИЛАЯ НЕДВИЖИМОСТЬ</p><h1>Место для<br>вашей жизни.</h1><a class="primary-action" href="#catalogue">Найти квартиру ↗</a></div>${photo('apartment','Светлый интерьер квартиры')}</section><section class="property-catalogue" id="catalogue"><div class="catalogue-heading"><h2>Подбор с вниманием<br>к деталям</h2>${S}</div>${T}${D}${R}</section></main>`;
case 'clinic':return `${nav('Приём','<a href="#workspace">Расписание</a><a href="#activity-section">История приёмов</a>')}<main id="workspace" class="clinic-page"><div class="clinic-title"><div><p>Регистратура · амбулаторный приём</p><h1>День в клинике</h1></div>${add('+ Записать пациента')}</div>${S}${T}${R}${dialog()}</main>`;
case 'event':return `<main id="workspace" class="event-studio"><aside class="event-poster"><a href="../index.html#work">← Портфолио</a><div><p>СМЕТА / СОБЫТИЯ</p><h1>ЛЮДИ.<br>ИДЕИ.<br>ВСТРЕЧИ.</h1><p>План камерной конференции</p></div><div class="poster-bottom"><strong>Один день.<br>Десятки деталей.</strong><a href="#activity-section">История расходов ↗</a></div></aside><section class="event-ledger"><header><p>Производство события</p><h2>Держим бюджет<br>под контролем.</h2></header>${S}<div class="expense-tools">${T}${add('+ Расход / лимит')}</div>${R}${dialog()}</section></main>`;
case 'editorial':return `${nav('Редакция','<a href="#workspace">Выпуск</a><a href="#activity-section">История правок</a>')}<main id="workspace" class="editorial-page"><header class="masthead"><p>Контент, который хочется читать</p><h1>Истории в работе.</h1><div>${S}${add('+ Написать материал')}</div></header>${T}${R}${dialog()}</main>`;
default:throw new Error('Missing domain composition: '+type);
}};